onedayoneline/oneday_user/urls.py
from django.urls import path
from . import views


app_name = 'user'


urlpatterns = [
    path('register/', views.register, name='register')
]

onedayoneline/onedayoneline/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oneday_user/', include('oneday_user.urls')),
    path('posts/', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
    path('login/', accounts_views.login, name='login')

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

onedayoneline/posts/urls.py
from django.urls import path

from . import views


app_name = "posts"


urlpatterns = [
    # ex: /posts/
    path('', views.index, name='index'),
    # ex: /posts/create
    path('create/', views.create, name='create'),
    # ex: /posts/5/
    path('<int:post_id>/', views.detail, name='detail'),
    # ex: /posts/5/update
    path('<int:post_id>/update', views.update, name='update'),
    # ex: /posts/5/delete
    path('<int:post_id>/delete', views.delete, name='delete'),

]

onedayoneline/accounts/models.py
from django.db import models

# Create your models here.

onedayoneline/oneday_user/models.py
from django.db import models

# Create your models here.


class Oneday_user(models.Model):
    username = models.CharField(max_length=64,
                                verbose_name='사용자명')
    useremail = models.EmailField(max_length=128,
                                  verbose_name='사용자이메일')
    password = models.CharField(max_length=64,
                                verbose_name='비밀번호')
    registered_dttm = models.DateTimeField(auto_now_add=True,
                                           verbose_name='등록시간')

    def __str__(self):
        return self.username

    class Meta:
        db_table = 'onedayoneline_user'
        verbose_name = '하루한줄 사용자'
        verbose_name_plural = '하루한줄 사용자'

onedayoneline/posts/models.py
import datetime
from django.db import models
from django.utils import timezone

class Post(models.Model):
    title_text = models.CharField(max_length=100) # 제목 -> 옵션 찾아보고 변경가능
    content_text = models.CharField(max_length=1000) # 내용 -> 옵션 찾아보고 변경가능
    pub_date = models.DateTimeField(auto_now_add=True) # 자동으로 오늘 날짜로 생성 -> 옵션 찾아보고 변경가능
    
    def __str__(self):
        return self.title_text

onedayoneline/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields  = [ 'title_text', 'content_text']

onedayoneline/accounts/views.py
from django.shortcuts import render

def login(request):
    if request.method == 'POST':
        pass
    else:
        return render(request, 'login.html')

onedayoneline/diary/views.py
from django.shortcuts import render

# Create your views here.

onedayoneline/oneday_user/views.py
from django.contrib.auth.hashers import make_password
from django.shortcuts import render
from .models import Oneday_user

# Create your views here.


def register(request):
    if request.method == 'GET':
        return render(request, 'register.html')
    elif request.method == 'POST':
        username = request.POST.get('username', None)     # username : register의 name 항목
        useremail = request.POST.get('useremail', None)
        password = request.POST.get('password', None)
        re_password = request.POST.get('re-password', None)

        res_data = {}

        if not (username and useremail and password and re_password):
            res_data['error'] = '모든 값을 입력해야 합니다.'
        elif password != re_password:
            res_data['error'] = '비밀번호가 다릅니다.'
        else:
            oneday_user = Oneday_user(
                username=username,
                useremail=useremail,
                password=make_password(password)
            )

            oneday_user.save()

        return render(request, 'register.html', res_data)

onedayoneline/posts/views.py
from django.shortcuts import render

from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from .forms import PostForm


# 제목리스트 -> 이 부분을 잘 고치면 달력모양이랑 합칠수 있지 않을까?
def index(request):
    post_list = Post.objects.all()
    context = {'post_list': post_list}
    return render(request, 'posts/index.html', context)

# 내용 상세 페이지
def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'posts/detail.html', {'post': post})

# 새로운 글 등록 -> 이부분도 달력모양에서 되게끔 하면 안되나?
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
        
    else:
        form = PostForm()
    
    return render(request, 'posts/create.html', {'form' : form})

# 글 수정
def update(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:detail', post_id)
        
    else:
        form = PostForm(instance=post)
    return render(request, 'posts/update.html', {'form': form})

# 글 삭제  -> 우리한테는 이 기능 없애려고 했어서 선택 필요

def delete(request, post_id):
    post = Post.objects.get(pk=post_id)
    post.delete()
    return redirect('posts:index')

onedayoneline/oneday_user/templates/register.html
{% extends "base.html" %}
{% block content %}
<script type="text/javascript">
    function checkPasswordMatch() {
        var password = $("#password").val();
        var confirmPassword = $("#re-password").val();

        if (password != confirmPassword)
            $("#errorMessage").html("비밀번호가 동일하지 않습니다.");
        else
            $("#errorMessage").html("비밀번호가 동일합니다.");
    }
    $(document).ready(function () {
       $("#password, #re-password").keyup(checkPasswordMatch);
    });

    var userFlag = false;
    var passFlag = false;
    var emailFlag = false;

    function checkUsername(){
      var name = document.forms["RegistrationForm"]["username"].value;
      if(name == ""){
        userFlag = true;
      }
    }

    function checkPassword(){
      var password = document.forms["RegistrationForm"]["password"].value;
      if(password == ""){
        passFlag = true;
      }
    }

    function checkEmail(){
      var email = document.forms["RegistrationForm"]["useremail"].value;
      if(email == ""){
        emailFlag = true;
      }
    }

    function formIsValid(){
      checkUsername();
      if (userFlag){
        $("#errorMessage").html("사용자 이름을 입력해주세요");
       return false;
      }
      checkPassword();
      if (passFlag){
        $("#errorMessage").html("비밀번호를 입력해주세요");
       return false;
      }
      checkEmail();
      if (emailFlag){
        $("#errorMessage").html("이메일을 입력해주세요");
       return false;
      }
    }
</script>
<article id="create" class="panel">
    <section>
        <div class="col-12">
            <header>
                <h3>회원가입</h3>
            </header>
        </div>
        <form action="." method="POST" onsubmit="return formIsValid()" class="RegistrationForm" name="RegistrationForm">
            <div>
                <div class="row">
                    <!--https://getbootstrap.com/docs/4.3/components/forms/ 에서 Overview-->
                    {% csrf_token %}    <!--다른 곳에서 호출할 수 없게 막는 기능, django에서는 기본값이라 안쓰면 에러남-->
                    <div class="col-12 col-12-medium">
                        <label for="username">ID</label>
                    </div>
                    <div class="col-6 col-12-medium">
                        <input type="text"
                               class="form-control"
                               id="username"
                               placeholder="ID"
                               name="username">
                    </div>
                    <div class="col-6 col-12-medium">
                        <p class="small_alarm">ID 중복 확인을 해주세요.</p>
                    </div>
                    <div class="col-6 col-12-medium">
                        <input type="submit" value="ID 중복 확인" class="left_small_btn">
                    </div>
                    <div class="col-12">
                        <label for="useremail">Email</label>
                        <input type="email"
                               class="form-control"
                               id="useremail"
                               placeholder="Email"
                               name="useremail">
                    </div>
                    <div class="col-12 col-12-medium">
                        <label for="password">Password</label>
                        <input type="password"
                               class="form-control"
                               id="password"
                               placeholder="Password"
                               name="password">
                    </div>
                    <div class="col-12 col-12-medium">
                        <label for="re-password">Password check</label>
                        <input type="password"
                               class="form-control"
                               id="re-password"
                               placeholder="Password check"
                               name="re-password">
                    </div>
                    <div class="col-6 col-12-medium">
                        <p id="errorMessage" class="animation small_alarm">
                            {{error}}   <!--views.py의 res_data['error']와 연결됨-->
                        <p>
                    </div>
                    <div class="col-6 col-12-medium">
                        <input type="submit" value="Sign-Up" class="right_normal_btn">
                    </div>
                </div>
            </div>
        </form>
    </section>
    <section>

    </section>
</article>
{% endblock %}

onedayoneline/onedayoneline/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/odol.css' %}">
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/browser.min.js' %}"></script>
    <script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script src="{% static 'assets/js/util.js' %}"></script>
</head>

<body class>
    <div id="wrapper">
        <div class="header">
            {% include "info.html" %}
        </div>
        <div class="nav">
            {% include "nav.html" %}
        </div>
        <div id="main">
            {% block content %}
            {% endblock %}
        </div>
        <div id="footer">
            {% include "footer.html" %}
        </div>
    </div>
</body>

</html>

onedayoneline/onedayoneline/templates/footer.html
<ul class="copyright">
	<li>© ODOL</li><li>Github: <a href="https://github.com/LazyerIJ/OneDayOneLine">OneDayOneLine</a></li>
</ul>

onedayoneline/onedayoneline/templates/info.html
<div class="header_title">
     <h2>하루한줄</h2>
</div>

onedayoneline/onedayoneline/templates/nav.html
<nav id="nav">
	<a href="{% url 'posts:index' %}" class="icon solid fa-home" id="home"><span>home</span></a>
	<a href="{% url 'posts:create' %}" class="icon solid fa-folder" id="create"><span>index</span></a>
	<a href="{% url 'user:register' %}" class="icon solid fa-envelope" id="register"><span>create</span></a>
</nav>
<script>
var $href = document.getElementById("home").href;
var $pathname = window.location.pathname;
var $flag = $href.includes($pathname);
$nav = $('#nav')
$nav_links = $nav.children('a');

for (var i=0; i<$nav_links.length; i++){
	var nav_link = $nav_links[i];
	var flag = nav_link.href.endsWith($pathname);
	if (flag) {
		nav_link.classList.add('active');
	}
}
</script>

onedayoneline/posts/templates/posts/create.html
{% extends "base.html" %}
{% block content %}
<article id="create" class="panel">
    <section>
        <div class="row">
            <div class="col-12 col-12-medium col-12-small">
                <header>
                    <h3>일기쓰기</h3>
                </header>
            </div>
            <div class="col-12 col-12-medium col-12-small">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <br>
                    <input type="submit" value="등록하기" class="right_normal_btn">
                </form>
            </div>
        </div>
    </section>
</article>
{% endblock %}

onedayoneline/posts/templates/posts/detail.html
{% extends "base.html" %}
{% block content %}
<article id="detail" class="panel">
    <section>
        <div class="row">
            <div class="col-12 col-12-medium col-12-small">
                <header>
                    <h3>{{ post.title_text }}</h3>
                </header>
            </div>
            <div class="col-12 col-12-medium col-12-small">
                <p>{{ post.pub_date }}</p>
            </div>
            <div class="col-12 col-12-medium col-12-small">
                {{ post.content_text }}
            </div>
            <div>
                <p>
                    <a href="{% url 'posts:update' post.id %}">수정</a>
                    <a href="{% url 'posts:delete' post.id %}">삭제</a>
                </p>
            </div>
        </div>
    </section>
</article>
{% endblock %}

onedayoneline/posts/templates/posts/index.html
{% extends "base.html" %}
{% block content %}
<a href="{% url 'login' %}">Login</a>
<article id="index" class="panel">
    <section>
        <div class="row">
            <div class="col-12">
                <header>
                    <h3>일기목록</h3>
                </header>
            </div>
            {% if post_list %}
                {% for post in post_list %}
                <div class="col-12 col-12-medium col-12-small">
                    <a class="normal_a" href="{% url 'posts:detail' post.id %}">
                    <h3>
                        {{ post.title_text }}
                    </h3>
                    <p>
                        {{ post.pub_date }};
                    </p>
                    <p>
                        {{ post.content_text }}
                    </p>
                    </a>
                </div>
                {% endfor %}
            {% else %}
            <p>No posts are available.</p>
            {% endif %}
        </div>
    </section>
</article>
{% endblock %}

onedayoneline/posts/templates/posts/update.html
# diarySite\posts\templates\posts\update.html
{% extends "base.html" %}
{% block content %}
<article id="create" class="panel">
    <section>
        <div class="row">
            <div class="col-12 col-12-medium col-12-small">
                <header>
                    <h3>수정하기</h3>
                </header>
            </div>
            <div class="col-12 col-12-medium col-12-small">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <br>
                    <input type="submit" value="수정하기">
                </form>
            </div>
        </div>
    </section>
</article>
{% endblock %}